# Book settings
title: The Data Science Interview Book
author: Somnath Rakshit | © MIT License - 2022 and onwards
copyright: "MIT License"  # Copyright year to be placed in the footer
logo: logo.gif
email: "somnath52@gmail.com"

latex:
  latex_documents:
    targetname: book.tex
#######################################################################################
# HTML-specific settings
html:
  favicon                   : "logo.gif"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://ml.pages.dev/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  extra_footer: 
  comments:
    hypothesis              : false
    utterances              : false
repository:
  url                       : https://github.com/somnathrakshit/mymlrecipes  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
sphinx:
  config:
    html_baseurl            : 'https://ml.pages.dev/'
    html_show_copyright     : false
  extra_extensions:
    - sphinx_sitemap